// Import required modules
const express = require('express');
const nodemailer = require('nodemailer');
const dotenv = require('dotenv');
const cors = require('cors'); // Import cors
const { getJobRoleInquiry } = require("./mail/templates/jobRole");
const { getInternshipInquiry } = require("./mail/templates/mailSender"); // Email template for recipient

//const { getFeedback } = require("../mail/templates/feedback"); // Email template for admin/feedback
const mailSender = require("./utils/mailsender"); // Utility function to send emails

// Initialize environment variables
dotenv.config();


// Create an Express application
const app = express();
// Enable CORS for all origins
app.use(cors());
const PORT = process.env.PORT || 3000;

// Middleware to parse JSON from incoming requests
app.use(express.json());

// Configure nodemailer transporter using environment variables
const transporter = nodemailer.createTransport({
  host: process.env.MAIL_HOST, // SMTP server
  port: 587, // Port for TLS
  secure: false, // Use STARTTLS
  auth: {
    user: process.env.MAIL_USER, // Your email
    pass: process.env.MAIL_PASS, // Your app password
  },
});

// API Endpoint to handle sending email
app.post('/send-email', async (req, res) => {
  console.log('Request received at /send-email'); // Debugging log
  console.log('Request body:', req.body); // Log request body

  try {
    const { recipientName, recipientEmail, recipientCompany,jobRole } = req.body;

    // Validate required fields
    if (!recipientName || !recipientEmail || !recipientCompany) {
      return res.status(400).json({ message: 'All fields are required.' });
    }

    // // Create email content for the recipient
    // const emailContent = getInternshipInquiry(recipientName, recipientCompany);

    // // Send email to the recipient
    // const emailRes = await mailSender(
    //   recipientEmail, // Recipient email address
    //   "Inquiry About Internship Opportunities", // Subject
    //   emailContent // HTML content generated by the template
    // );

    // Send confirmation email to admin/support team
    // const adminEmailContent = getFeedback(recipientName, recipientEmail, recipientCompany);
    // const emailRes2 = await mailSender(
    //   process.env.MAIL_USER, // Admin email (from .env)
    //   "You Got Some Feedback Regarding Contact Form", // Admin email subject
    //   adminEmailContent // HTML content for admin
    // );
    // Determine the email content template based on the presence of jobRole
    let emailContent;
    if (jobRole) {
      // Use the job role inquiry template
      emailContent = getJobRoleInquiry(recipientName, recipientCompany, jobRole);
    } else {
      // Use the general internship inquiry template
      emailContent = getInternshipInquiry(recipientName, recipientCompany);
    }

    // Send email to the recipient
    const emailRes = await mailSender(
      recipientEmail, // Recipient email address
      jobRole
        ? `Inquiry About ${jobRole} Opportunity` // Custom subject for job role
        : "Inquiry About Internship Opportunities", // Default subject
      emailContent // HTML content generated by the selected template
    );

    console.log("User Email Response:", emailRes);
   // console.log("Admin Email Response:", emailRes2);

    return res.json({
      success: true,
      message: "Email sent successfully!",
    });
  } catch (error) {
    console.error("Error sending email:", error.message);
    return res.status(500).json({
      success: false,
      message: "Something went wrong while sending the email",
    });
  }
});

// Start the server
app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});
